### ISSUE TITLE
Hardcoded prefix in usage messages

### ISSUE THREAD

**Issue by bramhaag** [sponges/dabBot#16]
https://github.com/sponges/dabBot/blob/master/src/main/java/ovh/not/javamusicbot/command/RadioCommand.java#L23

smh spong.

**Comment by sponges** [comment]
(the prefix is hard coded to prevent "help my bot dont work!!!! i do !!!help and no happen!!")

**Comment by bramhaag** [comment]
Not sure if the regex function from the config is actually used, but if it is, the prefix is changeable. Therefore, it shouldn't be hardcoded

**Comment by sponges** [comment]
Regex pattern isn't there for changing the prefix. It's for how it parses the messages.
For example, the pattern could permit messages like `hi my name is !!!help`.
I see your point but I don't want to support multiple prefixes.
